name: isolate_timer
description: A simple timer logic running in an isolate. Built with BLoC.
version: 1.0.0+1
repository: https://github.com/Venusdjinni/isolate_timer
issue_tracker: https://github.com/Venusdjinni/isolate_timer/issues
homepage: https://github.com/Venusdjinni/isolate_timer
topics: [bloc, timer, countdown]

environment:
  sdk: ^3.2.3

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
